# version: '3'
services:
  destination_service:
    build: ./destination_service
    ports:
      - "5001:5000"
  user_service:
    build: ./user_service
    ports:
      - "5002:5000"
  authentication_service:
    build: ./authentication_service
    ports:
      - "5003:5000"
  gateway:
    build: ./gateway
    ports:
      - "5000:5000"
